### ISSUE TITLE
Some URLs point to nothing

### ISSUE THREAD

**Issue by Telokis** [hcengineering/huly-selfhost#27]
For the `front` service, the following environment variables are defined ([Here](https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L80-L82)):
```yml
      - CALENDAR_URL=http://${SERVER_ADDRESS}:8095
      - GMAIL_URL=http://${SERVER_ADDRESS}:8088
      - TELEGRAM_URL=http://${SERVER_ADDRESS}:8086
```

However, there are no services associated with these ports, making the deployment either wrong or incomplete.  
This is not mentioned in the README.

**Comment by zaroot** [comment]
@veryCrunchy 
How is that pull request fixing the missing services? I've checked your pull request but I failed to see how this fixes the missing services so (if you can) please advise on this.

Note: I was expecting to see these services defined somewhere because just adding them in nginx without having any backend to serve requests for those URLs is still incomplete imo.
